version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  scraper:
    build:
      context: .
    container_name: scraper
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
      TARGET_URL: https://www.vesselfinder.com/ship-photos/117574
      TOPIC: image-data
    networks:
      - default
    
  postgres_consumer:
    image: postgres:15
    container_name: postgres_consumer
    environment:
      POSTGRES_USER: consumer_user
      POSTGRES_PASSWORD: consumer_password
      POSTGRES_DB: consumer_db
    ports:
      - "5434:5432" # Dedicated port for this new database
    volumes:
      - postgres-consumer-data:/var/lib/postgresql/data

  consumer:
    build:
      context: ./consumer
    container_name: consumer
    depends_on:
      - kafka
      - postgres_consumer
    environment:
      KAFKA_BROKER: kafka:9092
      TOPIC: image-data
      POSTGRES_HOST: postgres_consumer
      POSTGRES_PORT: 5432
      POSTGRES_USER: consumer_user
      POSTGRES_PASSWORD: consumer_password
      POSTGRES_DB: consumer_db
    networks:
      - default

volumes:
  postgres-consumer-data:
